var searchData=
[
  ['sek_0',['Pastaba: Kiekvienas greitis - vidutinis 3 testu laikas (sek.).',['../md__r_e_a_d_m_e.html#autotoc_md23',1,'']]],
  ['sek_20_3a_1',['sek :',['../md__r_e_a_d_m_e.html#autotoc_md32',1,'Nuskaitymas (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md37',1,'Nuskaitymas (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md42',1,'Nuskaitymas (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md47',1,'Nuskaitymas (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md52',1,'Nuskaitymas (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md33',1,'Rusiavimas faile (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md38',1,'Rusiavimas faile (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md43',1,'Rusiavimas faile (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md48',1,'Rusiavimas faile (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md53',1,'Rusiavimas faile (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md34',1,'Rusiavimas i kietekus ir vargsiukus (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md39',1,'Rusiavimas i kietekus ir vargsiukus (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md44',1,'Rusiavimas i kietekus ir vargsiukus (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md49',1,'Rusiavimas i kietekus ir vargsiukus (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md54',1,'Rusiavimas i kietekus ir vargsiukus (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md35',1,'Vidurkiai (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md40',1,'Vidurkiai (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md45',1,'Vidurkiai (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md50',1,'Vidurkiai (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md55',1,'Vidurkiai (sek.):']]],
  ['sek_20programoje_20naudojamas_20konteineris_20vektorius_20paleidziama_203_20strategija_2',['Pastaba: Kiekvienas greitis - vidutinis 3 testu laikas (sek.). Programoje naudojamas konteineris - vektorius. Paleidziama 3 strategija.',['../md__r_e_a_d_m_e.html#autotoc_md28',1,'']]],
  ['sekundemis_3',['Pastaba: laikas matuojamas sekundemis.',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]],
  ['sena_4',['V1.0 versijos testavimai (Sena)',['../md__r_e_a_d_m_e.html#autotoc_md29',1,'']]],
  ['std_3a_3avector_20ir_20mano_20vektoriaus_20klases_20vidutinio_20programos_20veikimo_20laiko_20palyginimas_5',['std::vector ir mano vektoriaus klases vidutinio programos veikimo laiko palyginimas',['../md__r_e_a_d_m_e.html#autotoc_md22',1,'']]],
  ['strategija_6',['strategija',['../md__r_e_a_d_m_e.html#autotoc_md57',1,'1 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md83',1,'2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md109',1,'3 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md28',1,'Pastaba: Kiekvienas greitis - vidutinis 3 testu laikas (sek.). Programoje naudojamas konteineris - vektorius. Paleidziama 3 strategija.']]],
  ['strategiju_20rezultatai_7',['Programos rusiavimo i kietekus ir vargsiukus greitis priklausomai nuo strategiju rezultatai',['../md__r_e_a_d_m_e.html#autotoc_md56',1,'']]],
  ['studentų_20analizė_8',['1000 Studentų analizė',['../md__r_e_a_d_m_e.html#autotoc_md31',1,'']]],
  ['studentas_9',['Studentas',['../class_studentas.html',1,'']]],
  ['studentu_20analize_10',['Studentu analize',['../md__r_e_a_d_m_e.html#autotoc_md58',1,'1000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md84',1,'1000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md110',1,'1000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md36',1,'10000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md63',1,'10000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md89',1,'10000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md115',1,'10000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md41',1,'100000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md68',1,'100000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md94',1,'100000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md120',1,'100000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md46',1,'1000000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md73',1,'1000000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md99',1,'1000000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md125',1,'1000000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md51',1,'10000000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md78',1,'10000000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md104',1,'10000000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md130',1,'10000000 Studentu analize']]],
  ['su_20v1_200_20versija_20nauja_11',['V1.1 versijos testavimai ir palyginimas su V1.0 versija (Nauja)',['../md__r_e_a_d_m_e.html#autotoc_md27',1,'']]]
];
