var searchData=
[
  ['naudojamas_20konteineris_20vektorius_20paleidziama_203_20strategija_0',['Pastaba: Kiekvienas greitis - vidutinis 3 testu laikas (sek.). Programoje naudojamas konteineris - vektorius. Paleidziama 3 strategija.',['../md__r_e_a_d_m_e.html#autotoc_md28',1,'']]],
  ['naudojimosi_20instrukcijos_1',['📃 Programos naudojimosi instrukcijos',['../md__r_e_a_d_m_e.html#autotoc_md3',1,'']]],
  ['nauja_2',['V1.1 versijos testavimai ir palyginimas su V1.0 versija (Nauja)',['../md__r_e_a_d_m_e.html#autotoc_md27',1,'']]],
  ['nuo_20strategiju_20rezultatai_3',['Programos rusiavimo i kietekus ir vargsiukus greitis priklausomai nuo strategiju rezultatai',['../md__r_e_a_d_m_e.html#autotoc_md56',1,'']]],
  ['nuotraukos_4',['Nuotraukos',['../md__r_e_a_d_m_e.html#autotoc_md59',1,'Nuotraukos'],['../md__r_e_a_d_m_e.html#autotoc_md64',1,'Nuotraukos'],['../md__r_e_a_d_m_e.html#autotoc_md69',1,'Nuotraukos'],['../md__r_e_a_d_m_e.html#autotoc_md74',1,'Nuotraukos'],['../md__r_e_a_d_m_e.html#autotoc_md79',1,'Nuotraukos'],['../md__r_e_a_d_m_e.html#autotoc_md85',1,'Nuotraukos'],['../md__r_e_a_d_m_e.html#autotoc_md90',1,'Nuotraukos'],['../md__r_e_a_d_m_e.html#autotoc_md95',1,'Nuotraukos'],['../md__r_e_a_d_m_e.html#autotoc_md100',1,'Nuotraukos'],['../md__r_e_a_d_m_e.html#autotoc_md105',1,'Nuotraukos'],['../md__r_e_a_d_m_e.html#autotoc_md111',1,'Nuotraukos'],['../md__r_e_a_d_m_e.html#autotoc_md116',1,'Nuotraukos'],['../md__r_e_a_d_m_e.html#autotoc_md121',1,'Nuotraukos'],['../md__r_e_a_d_m_e.html#autotoc_md126',1,'Nuotraukos'],['../md__r_e_a_d_m_e.html#autotoc_md131',1,'Nuotraukos']]],
  ['nuskaitymas_20sek_20_3a_5',['Nuskaitymas sek :',['../md__r_e_a_d_m_e.html#autotoc_md32',1,'Nuskaitymas (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md37',1,'Nuskaitymas (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md42',1,'Nuskaitymas (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md47',1,'Nuskaitymas (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md52',1,'Nuskaitymas (sek.):']]]
];
