var searchData=
[
  ['v_20pradine_20versija_0',['v.pradine versija',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]],
  ['v0_201_20versija_1',['v0.1 versija',['../md__r_e_a_d_m_e.html#autotoc_md8',1,'']]],
  ['v0_202_20versija_2',['v0.2 versija',['../md__r_e_a_d_m_e.html#autotoc_md9',1,'']]],
  ['v0_203_20versija_3',['v0.3 versija',['../md__r_e_a_d_m_e.html#autotoc_md10',1,'']]],
  ['v0_204_20versija_4',['v0.4 versija',['../md__r_e_a_d_m_e.html#autotoc_md11',1,'']]],
  ['v1_200_20pradine_20versija_5',['v1.0 pradine versija',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'']]],
  ['v1_200_20release_6',['Programos testavimo rezultatai pradiniam v1.0 release',['../md__r_e_a_d_m_e.html#autotoc_md30',1,'']]],
  ['v1_200_20versija_7',['v1.0 versija',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'']]],
  ['v1_200_20versija_20nauja_8',['V1.1 versijos testavimai ir palyginimas su V1.0 versija (Nauja)',['../md__r_e_a_d_m_e.html#autotoc_md27',1,'']]],
  ['v1_200_20versijos_20testavimai_20sena_9',['V1.0 versijos testavimai (Sena)',['../md__r_e_a_d_m_e.html#autotoc_md29',1,'']]],
  ['v1_201_20versija_10',['v1.1 versija',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'']]],
  ['v1_201_20versijos_20testavimai_20ir_20palyginimas_20su_20v1_200_20versija_20nauja_11',['V1.1 versijos testavimai ir palyginimas su V1.0 versija (Nauja)',['../md__r_e_a_d_m_e.html#autotoc_md27',1,'']]],
  ['v1_202_20versija_12',['v1.2 versija',['../md__r_e_a_d_m_e.html#autotoc_md15',1,'']]],
  ['v1_205_20versija_13',['v1.5 versija',['../md__r_e_a_d_m_e.html#autotoc_md16',1,'']]],
  ['v2_200_20versija_14',['v2.0 versija',['../md__r_e_a_d_m_e.html#autotoc_md17',1,'']]],
  ['v3_200_20versija_15',['v3.0 versija',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['v3_200_20versijos_20testavimas_16',['v3.0 versijos testavimas',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['vargsiukus_20greitis_20priklausomai_20nuo_20strategiju_20rezultatai_17',['Programos rusiavimo i kietekus ir vargsiukus greitis priklausomai nuo strategiju rezultatai',['../md__r_e_a_d_m_e.html#autotoc_md56',1,'']]],
  ['vargsiukus_20sek_20_3a_18',['vargsiukus sek :',['../md__r_e_a_d_m_e.html#autotoc_md34',1,'Rusiavimas i kietekus ir vargsiukus (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md39',1,'Rusiavimas i kietekus ir vargsiukus (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md44',1,'Rusiavimas i kietekus ir vargsiukus (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md49',1,'Rusiavimas i kietekus ir vargsiukus (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md54',1,'Rusiavimas i kietekus ir vargsiukus (sek.):']]],
  ['vector_19',['Vector',['../md__r_e_a_d_m_e.html#autotoc_md60',1,'Vector'],['../md__r_e_a_d_m_e.html#autotoc_md65',1,'Vector'],['../md__r_e_a_d_m_e.html#autotoc_md70',1,'Vector'],['../md__r_e_a_d_m_e.html#autotoc_md75',1,'Vector'],['../md__r_e_a_d_m_e.html#autotoc_md80',1,'Vector'],['../md__r_e_a_d_m_e.html#autotoc_md86',1,'Vector'],['../md__r_e_a_d_m_e.html#autotoc_md91',1,'Vector'],['../md__r_e_a_d_m_e.html#autotoc_md96',1,'Vector'],['../md__r_e_a_d_m_e.html#autotoc_md101',1,'Vector'],['../md__r_e_a_d_m_e.html#autotoc_md106',1,'Vector'],['../md__r_e_a_d_m_e.html#autotoc_md112',1,'Vector'],['../md__r_e_a_d_m_e.html#autotoc_md117',1,'Vector'],['../md__r_e_a_d_m_e.html#autotoc_md122',1,'Vector'],['../md__r_e_a_d_m_e.html#autotoc_md127',1,'Vector'],['../md__r_e_a_d_m_e.html#autotoc_md132',1,'Vector']]],
  ['vector_20',['vector',['../classvector.html',1,'']]],
  ['vector_3c_20int_20_3e_21',['vector&lt; int &gt;',['../classvector.html',1,'']]],
  ['veikimo_20laiko_20palyginimas_22',['std::vector ir mano vektoriaus klases vidutinio programos veikimo laiko palyginimas',['../md__r_e_a_d_m_e.html#autotoc_md22',1,'']]],
  ['vektoriaus_20klases_20vidutinio_20programos_20veikimo_20laiko_20palyginimas_23',['std::vector ir mano vektoriaus klases vidutinio programos veikimo laiko palyginimas',['../md__r_e_a_d_m_e.html#autotoc_md22',1,'']]],
  ['vektorius_20paleidziama_203_20strategija_24',['Pastaba: Kiekvienas greitis - vidutinis 3 testu laikas (sek.). Programoje naudojamas konteineris - vektorius. Paleidziama 3 strategija.',['../md__r_e_a_d_m_e.html#autotoc_md28',1,'']]],
  ['versija_25',['versija',['../md__r_e_a_d_m_e.html',1,'Trecia versija'],['../md__r_e_a_d_m_e.html#autotoc_md7',1,'v.pradine versija'],['../md__r_e_a_d_m_e.html#autotoc_md8',1,'v0.1 versija'],['../md__r_e_a_d_m_e.html#autotoc_md9',1,'v0.2 versija'],['../md__r_e_a_d_m_e.html#autotoc_md10',1,'v0.3 versija'],['../md__r_e_a_d_m_e.html#autotoc_md11',1,'v0.4 versija'],['../md__r_e_a_d_m_e.html#autotoc_md12',1,'v1.0 pradine versija'],['../md__r_e_a_d_m_e.html#autotoc_md13',1,'v1.0 versija'],['../md__r_e_a_d_m_e.html#autotoc_md14',1,'v1.1 versija'],['../md__r_e_a_d_m_e.html#autotoc_md15',1,'v1.2 versija'],['../md__r_e_a_d_m_e.html#autotoc_md16',1,'v1.5 versija'],['../md__r_e_a_d_m_e.html#autotoc_md17',1,'v2.0 versija'],['../md__r_e_a_d_m_e.html#autotoc_md18',1,'v3.0 versija']]],
  ['versija_20nauja_26',['V1.1 versijos testavimai ir palyginimas su V1.0 versija (Nauja)',['../md__r_e_a_d_m_e.html#autotoc_md27',1,'']]],
  ['versijos_20testavimai_20ir_20palyginimas_20su_20v1_200_20versija_20nauja_27',['V1.1 versijos testavimai ir palyginimas su V1.0 versija (Nauja)',['../md__r_e_a_d_m_e.html#autotoc_md27',1,'']]],
  ['versijos_20testavimai_20sena_28',['V1.0 versijos testavimai (Sena)',['../md__r_e_a_d_m_e.html#autotoc_md29',1,'']]],
  ['versijos_20testavimas_29',['v3.0 versijos testavimas',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['vidurkiai_20sek_20_3a_30',['Vidurkiai sek :',['../md__r_e_a_d_m_e.html#autotoc_md35',1,'Vidurkiai (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md40',1,'Vidurkiai (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md45',1,'Vidurkiai (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md50',1,'Vidurkiai (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md55',1,'Vidurkiai (sek.):']]],
  ['vidutinio_20programos_20veikimo_20laiko_20palyginimas_31',['std::vector ir mano vektoriaus klases vidutinio programos veikimo laiko palyginimas',['../md__r_e_a_d_m_e.html#autotoc_md22',1,'']]],
  ['vidutinis_203_20testu_20laikas_20sek_32',['Pastaba: Kiekvienas greitis - vidutinis 3 testu laikas (sek.).',['../md__r_e_a_d_m_e.html#autotoc_md23',1,'']]],
  ['vidutinis_203_20testu_20laikas_20sek_20programoje_20naudojamas_20konteineris_20vektorius_20paleidziama_203_20strategija_33',['Pastaba: Kiekvienas greitis - vidutinis 3 testu laikas (sek.). Programoje naudojamas konteineris - vektorius. Paleidziama 3 strategija.',['../md__r_e_a_d_m_e.html#autotoc_md28',1,'']]]
];
