var searchData=
[
  ['sek_20_3a_0',['sek :',['../md__r_e_a_d_m_e.html#autotoc_md25',1,'Nuskaitymas (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md30',1,'Nuskaitymas (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md35',1,'Nuskaitymas (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md40',1,'Nuskaitymas (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md45',1,'Nuskaitymas (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md26',1,'Rusiavimas faile (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md31',1,'Rusiavimas faile (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md36',1,'Rusiavimas faile (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md41',1,'Rusiavimas faile (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md46',1,'Rusiavimas faile (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md27',1,'Rusiavimas i kietekus ir vargsiukus (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md32',1,'Rusiavimas i kietekus ir vargsiukus (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md37',1,'Rusiavimas i kietekus ir vargsiukus (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md42',1,'Rusiavimas i kietekus ir vargsiukus (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md47',1,'Rusiavimas i kietekus ir vargsiukus (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md28',1,'Vidurkiai (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md33',1,'Vidurkiai (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md38',1,'Vidurkiai (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md43',1,'Vidurkiai (sek.):'],['../md__r_e_a_d_m_e.html#autotoc_md48',1,'Vidurkiai (sek.):']]],
  ['sek_20programoje_20naudojamas_20konteineris_20vektorius_20paleidziama_203_20strategija_1',['Pastaba: Kiekvienas greitis - vidutinis 3 testu laikas (sek.). Programoje naudojamas konteineris - vektorius. Paleidziama 3 strategija.',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]],
  ['sena_2',['V1.0 versijos testavimai (Sena)',['../md__r_e_a_d_m_e.html#autotoc_md22',1,'']]],
  ['strategija_3',['strategija',['../md__r_e_a_d_m_e.html#autotoc_md50',1,'1 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md76',1,'2 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md102',1,'3 strategija'],['../md__r_e_a_d_m_e.html#autotoc_md21',1,'Pastaba: Kiekvienas greitis - vidutinis 3 testu laikas (sek.). Programoje naudojamas konteineris - vektorius. Paleidziama 3 strategija.']]],
  ['strategiju_20rezultatai_4',['Programos rusiavimo i kietekus ir vargsiukus greitis priklausomai nuo strategiju rezultatai',['../md__r_e_a_d_m_e.html#autotoc_md49',1,'']]],
  ['studentų_20analizė_5',['1000 Studentų analizė',['../md__r_e_a_d_m_e.html#autotoc_md24',1,'']]],
  ['studentas_6',['Studentas',['../class_studentas.html',1,'']]],
  ['studentu_20analize_7',['Studentu analize',['../md__r_e_a_d_m_e.html#autotoc_md51',1,'1000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md77',1,'1000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md103',1,'1000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md29',1,'10000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md56',1,'10000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md82',1,'10000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md108',1,'10000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md34',1,'100000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md61',1,'100000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md87',1,'100000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md113',1,'100000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md39',1,'1000000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md66',1,'1000000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md92',1,'1000000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md118',1,'1000000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md44',1,'10000000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md71',1,'10000000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md97',1,'10000000 Studentu analize'],['../md__r_e_a_d_m_e.html#autotoc_md123',1,'10000000 Studentu analize']]],
  ['su_20v1_200_20versija_20nauja_8',['V1.1 versijos testavimai ir palyginimas su V1.0 versija (Nauja)',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]]
];
